[2025-10-23T07:00:03.427+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-23T07:00:03.446+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flood_prediction_pipeline.predict_and_log scheduled__2025-10-23T06:55:00+00:00 [queued]>
[2025-10-23T07:00:03.452+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flood_prediction_pipeline.predict_and_log scheduled__2025-10-23T06:55:00+00:00 [queued]>
[2025-10-23T07:00:03.453+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-10-23T07:00:03.463+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): predict_and_log> on 2025-10-23 06:55:00+00:00
[2025-10-23T07:00:03.470+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=376) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-10-23T07:00:03.470+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'flood_prediction_pipeline', 'predict_and_log', 'scheduled__2025-10-23T06:55:00+00:00', '--job-id', '427', '--raw', '--subdir', 'DAGS_FOLDER/flood_prediction_dag.py', '--cfg-path', '/tmp/tmpd57a4sjg']
[2025-10-23T07:00:03.471+0000] {standard_task_runner.py:63} INFO - Started process 379 to run task
[2025-10-23T07:00:03.471+0000] {standard_task_runner.py:91} INFO - Job 427: Subtask predict_and_log
[2025-10-23T07:00:03.505+0000] {task_command.py:426} INFO - Running <TaskInstance: flood_prediction_pipeline.predict_and_log scheduled__2025-10-23T06:55:00+00:00 [running]> on host d52a4bcac09b
[2025-10-23T07:00:03.567+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='flood_prediction_pipeline' AIRFLOW_CTX_TASK_ID='predict_and_log' AIRFLOW_CTX_EXECUTION_DATE='2025-10-23T06:55:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-23T06:55:00+00:00'
[2025-10-23T07:00:03.569+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-23T07:00:04.617+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/sklearn/ensemble/_base.py:168 UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
[2025-10-23T07:00:04.624+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/sklearn/ensemble/_base.py:168 UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
[2025-10-23T07:00:04.630+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/sklearn/ensemble/_base.py:168 UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
[2025-10-23T07:00:04.635+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/sklearn/ensemble/_base.py:168 UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
[2025-10-23T07:00:04.641+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/sklearn/ensemble/_base.py:168 UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
[2025-10-23T07:00:04.648+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/sklearn/ensemble/_base.py:168 UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
[2025-10-23T07:00:04.724+0000] {logging_mixin.py:188} INFO - âœ… Prediction logged: {'prediction': 1, 'probability': 0.687, 'timestamp': '2025-10-23_07-00-04', 'lat': 18.658001326472906, 'lon': 78.10284616737249, 'city': 'Nizamabad'}
[2025-10-23T07:00:04.733+0000] {python.py:237} INFO - Done. Returned value was: Prediction_Completed
[2025-10-23T07:00:04.734+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-23T07:00:04.746+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=flood_prediction_pipeline, task_id=predict_and_log, run_id=scheduled__2025-10-23T06:55:00+00:00, execution_date=20251023T065500, start_date=20251023T070003, end_date=20251023T070004
[2025-10-23T07:00:04.770+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-10-23T07:00:04.787+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-10-23T07:00:04.790+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
