[2025-10-20T14:30:03.697+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-20T14:30:03.716+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flood_prediction_pipeline.predict_and_log scheduled__2025-10-20T14:25:00+00:00 [queued]>
[2025-10-20T14:30:03.721+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flood_prediction_pipeline.predict_and_log scheduled__2025-10-20T14:25:00+00:00 [queued]>
[2025-10-20T14:30:03.722+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-10-20T14:30:03.734+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): predict_and_log> on 2025-10-20 14:25:00+00:00
[2025-10-20T14:30:03.740+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=3489) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-10-20T14:30:03.740+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'flood_prediction_pipeline', 'predict_and_log', 'scheduled__2025-10-20T14:25:00+00:00', '--job-id', '124', '--raw', '--subdir', 'DAGS_FOLDER/flood_prediction_dag.py', '--cfg-path', '/tmp/tmp4qwrcrfj']
[2025-10-20T14:30:03.742+0000] {standard_task_runner.py:63} INFO - Started process 3492 to run task
[2025-10-20T14:30:03.742+0000] {standard_task_runner.py:91} INFO - Job 124: Subtask predict_and_log
[2025-10-20T14:30:03.782+0000] {task_command.py:426} INFO - Running <TaskInstance: flood_prediction_pipeline.predict_and_log scheduled__2025-10-20T14:25:00+00:00 [running]> on host bc5f677806a4
[2025-10-20T14:30:03.853+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='flood_prediction_pipeline' AIRFLOW_CTX_TASK_ID='predict_and_log' AIRFLOW_CTX_EXECUTION_DATE='2025-10-20T14:25:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-20T14:25:00+00:00'
[2025-10-20T14:30:03.855+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-20T14:30:04.714+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/sklearn/ensemble/_base.py:168 UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
[2025-10-20T14:30:04.719+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/sklearn/ensemble/_base.py:168 UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
[2025-10-20T14:30:04.895+0000] {logging_mixin.py:188} INFO - ‚ÑπÔ∏è Starting MLflow run...
[2025-10-20T14:30:04.929+0000] {logging_mixin.py:188} WARNING - 2025/10/20 14:30:04 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2025-10-20T14:30:04.997+0000] {logging_mixin.py:188} INFO - ‚ÑπÔ∏è Inside MLflow run
[2025-10-20T14:30:05.264+0000] {logging_mixin.py:188} INFO - ‚úÖ MLflow run logged: 4cfb44a3fa6744a0b5d099143154c5c7
[2025-10-20T14:30:05.296+0000] {logging_mixin.py:188} INFO - üèÉ View run Live Flood Prediction at: http://mlflow:5000/#/experiments/1/runs/4cfb44a3fa6744a0b5d099143154c5c7
[2025-10-20T14:30:05.297+0000] {logging_mixin.py:188} INFO - üß™ View experiment at: http://mlflow:5000/#/experiments/1
[2025-10-20T14:30:05.328+0000] {logging_mixin.py:188} INFO - ‚úÖ Prediction logged: {'prediction': 1, 'probability': 0.99, 'timestamp': '2025-10-20 14:30:04', 'lat': 17.997416390715387, 'lon': 79.60385189512965, 'city': 'Warangal'}
[2025-10-20T14:30:05.329+0000] {python.py:237} INFO - Done. Returned value was: {'prediction': 1, 'probability': 0.99, 'timestamp': '2025-10-20 14:30:04', 'lat': 17.997416390715387, 'lon': 79.60385189512965, 'city': 'Warangal'}
[2025-10-20T14:30:05.329+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-20T14:30:05.351+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=flood_prediction_pipeline, task_id=predict_and_log, run_id=scheduled__2025-10-20T14:25:00+00:00, execution_date=20251020T142500, start_date=20251020T143003, end_date=20251020T143005
[2025-10-20T14:30:05.403+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-10-20T14:30:05.417+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-20T14:30:05.420+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
