[2025-10-29T20:00:03.451+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-29T20:00:03.473+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flood_prediction_pipeline.predict_and_log scheduled__2025-10-29T19:55:00+00:00 [queued]>
[2025-10-29T20:00:03.481+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flood_prediction_pipeline.predict_and_log scheduled__2025-10-29T19:55:00+00:00 [queued]>
[2025-10-29T20:00:03.483+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-10-29T20:00:03.498+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): predict_and_log> on 2025-10-29 19:55:00+00:00
[2025-10-29T20:00:03.506+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=22463) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-10-29T20:00:03.506+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'flood_prediction_pipeline', 'predict_and_log', 'scheduled__2025-10-29T19:55:00+00:00', '--job-id', '255', '--raw', '--subdir', 'DAGS_FOLDER/flood_prediction_dag.py', '--cfg-path', '/tmp/tmp1ywqp9dp']
[2025-10-29T20:00:03.508+0000] {standard_task_runner.py:63} INFO - Started process 22466 to run task
[2025-10-29T20:00:03.508+0000] {standard_task_runner.py:91} INFO - Job 255: Subtask predict_and_log
[2025-10-29T20:00:03.550+0000] {task_command.py:426} INFO - Running <TaskInstance: flood_prediction_pipeline.predict_and_log scheduled__2025-10-29T19:55:00+00:00 [running]> on host db3c1202c602
[2025-10-29T20:00:03.622+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='flood_prediction_pipeline' AIRFLOW_CTX_TASK_ID='predict_and_log' AIRFLOW_CTX_EXECUTION_DATE='2025-10-29T19:55:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-29T19:55:00+00:00'
[2025-10-29T20:00:03.624+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-29T20:00:05.161+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/sklearn/ensemble/_base.py:168 UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
[2025-10-29T20:00:05.168+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/sklearn/ensemble/_base.py:168 UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
[2025-10-29T20:00:05.174+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/sklearn/ensemble/_base.py:168 UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
[2025-10-29T20:00:05.295+0000] {logging_mixin.py:188} WARNING - 2025/10/29 20:00:05 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2025-10-29T20:00:05.626+0000] {logging_mixin.py:188} INFO - üèÉ View run LivePrediction_2025-10-29 20:00:05 at: http://mlflow:5000/#/experiments/1/runs/9132e5e86b9c4c8895e3e36568f4b491
[2025-10-29T20:00:05.627+0000] {logging_mixin.py:188} INFO - üß™ View experiment at: http://mlflow:5000/#/experiments/1
[2025-10-29T20:00:05.700+0000] {logging_mixin.py:188} INFO - ‚úÖ Prediction generated and logged.
[2025-10-29T20:00:05.702+0000] {python.py:237} INFO - Done. Returned value was: Prediction_Completed
[2025-10-29T20:00:05.703+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-29T20:00:05.718+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=flood_prediction_pipeline, task_id=predict_and_log, run_id=scheduled__2025-10-29T19:55:00+00:00, execution_date=20251029T195500, start_date=20251029T200003, end_date=20251029T200005
[2025-10-29T20:00:05.771+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-10-29T20:00:05.793+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-10-29T20:00:05.798+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
