[2025-10-29T15:55:06.528+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-29T15:55:06.552+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flood_prediction_pipeline.predict_and_log manual__2025-10-29T15:55:01.171027+00:00 [queued]>
[2025-10-29T15:55:06.560+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flood_prediction_pipeline.predict_and_log manual__2025-10-29T15:55:01.171027+00:00 [queued]>
[2025-10-29T15:55:06.561+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-10-29T15:55:06.573+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): predict_and_log> on 2025-10-29 15:55:01.171027+00:00
[2025-10-29T15:55:06.582+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2275) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-10-29T15:55:06.583+0000] {standard_task_runner.py:63} INFO - Started process 2288 to run task
[2025-10-29T15:55:06.583+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'flood_prediction_pipeline', 'predict_and_log', 'manual__2025-10-29T15:55:01.171027+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/flood_prediction_dag.py', '--cfg-path', '/tmp/tmpvc0nn4bh']
[2025-10-29T15:55:06.584+0000] {standard_task_runner.py:91} INFO - Job 57: Subtask predict_and_log
[2025-10-29T15:55:06.634+0000] {task_command.py:426} INFO - Running <TaskInstance: flood_prediction_pipeline.predict_and_log manual__2025-10-29T15:55:01.171027+00:00 [running]> on host db3c1202c602
[2025-10-29T15:55:06.724+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='flood_prediction_pipeline' AIRFLOW_CTX_TASK_ID='predict_and_log' AIRFLOW_CTX_EXECUTION_DATE='2025-10-29T15:55:01.171027+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-29T15:55:01.171027+00:00'
[2025-10-29T15:55:06.726+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-29T15:55:06.753+0000] {logging_mixin.py:188} INFO - ℹ️ Latest row already processed. Skipping prediction.
[2025-10-29T15:55:06.778+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-10-29T15:55:06.780+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-29T15:55:06.790+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=flood_prediction_pipeline, task_id=predict_and_log, run_id=manual__2025-10-29T15:55:01.171027+00:00, execution_date=20251029T155501, start_date=20251029T155506, end_date=20251029T155506
[2025-10-29T15:55:06.838+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-10-29T15:55:06.863+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-10-29T15:55:06.867+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
