[2025-10-20T14:45:03.189+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-20T14:45:03.207+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flood_prediction_pipeline.predict_and_log scheduled__2025-10-20T14:40:00+00:00 [queued]>
[2025-10-20T14:45:03.214+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flood_prediction_pipeline.predict_and_log scheduled__2025-10-20T14:40:00+00:00 [queued]>
[2025-10-20T14:45:03.215+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-10-20T14:45:03.226+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): predict_and_log> on 2025-10-20 14:40:00+00:00
[2025-10-20T14:45:03.233+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=3755) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-10-20T14:45:03.234+0000] {standard_task_runner.py:63} INFO - Started process 3761 to run task
[2025-10-20T14:45:03.233+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'flood_prediction_pipeline', 'predict_and_log', 'scheduled__2025-10-20T14:40:00+00:00', '--job-id', '130', '--raw', '--subdir', 'DAGS_FOLDER/flood_prediction_dag.py', '--cfg-path', '/tmp/tmp5flf0580']
[2025-10-20T14:45:03.235+0000] {standard_task_runner.py:91} INFO - Job 130: Subtask predict_and_log
[2025-10-20T14:45:03.274+0000] {task_command.py:426} INFO - Running <TaskInstance: flood_prediction_pipeline.predict_and_log scheduled__2025-10-20T14:40:00+00:00 [running]> on host bc5f677806a4
[2025-10-20T14:45:03.336+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='flood_prediction_pipeline' AIRFLOW_CTX_TASK_ID='predict_and_log' AIRFLOW_CTX_EXECUTION_DATE='2025-10-20T14:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-20T14:40:00+00:00'
[2025-10-20T14:45:03.337+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-20T14:45:04.122+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/sklearn/ensemble/_base.py:168 UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
[2025-10-20T14:45:04.128+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/sklearn/ensemble/_base.py:168 UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
[2025-10-20T14:45:04.289+0000] {logging_mixin.py:188} INFO - ‚ÑπÔ∏è Starting MLflow run...
[2025-10-20T14:45:04.328+0000] {logging_mixin.py:188} WARNING - 2025/10/20 14:45:04 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2025-10-20T14:45:04.420+0000] {logging_mixin.py:188} INFO - ‚ÑπÔ∏è Inside MLflow run
[2025-10-20T14:45:04.737+0000] {logging_mixin.py:188} INFO - ‚úÖ MLflow run logged: c2cbb936230d4f37a0c42e7122886bb5
[2025-10-20T14:45:04.773+0000] {logging_mixin.py:188} INFO - üèÉ View run Live Flood Prediction at: http://mlflow:5000/#/experiments/1/runs/c2cbb936230d4f37a0c42e7122886bb5
[2025-10-20T14:45:04.775+0000] {logging_mixin.py:188} INFO - üß™ View experiment at: http://mlflow:5000/#/experiments/1
[2025-10-20T14:45:04.812+0000] {logging_mixin.py:188} INFO - ‚úÖ Prediction logged: {'prediction': 1, 'probability': 0.98, 'timestamp': '2025-10-20 14:45:04', 'lat': 17.997416390715387, 'lon': 79.60385189512965, 'city': 'Warangal'}
[2025-10-20T14:45:04.813+0000] {python.py:237} INFO - Done. Returned value was: {'prediction': 1, 'probability': 0.98, 'timestamp': '2025-10-20 14:45:04', 'lat': 17.997416390715387, 'lon': 79.60385189512965, 'city': 'Warangal'}
[2025-10-20T14:45:04.814+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-20T14:45:04.835+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=flood_prediction_pipeline, task_id=predict_and_log, run_id=scheduled__2025-10-20T14:40:00+00:00, execution_date=20251020T144000, start_date=20251020T144503, end_date=20251020T144504
[2025-10-20T14:45:04.894+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-10-20T14:45:04.906+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-20T14:45:04.911+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
