[2025-10-19T10:55:05.345+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-19T10:55:05.389+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flood_prediction_pipeline.predict_and_log scheduled__2025-10-19T10:50:00+00:00 [queued]>
[2025-10-19T10:55:05.402+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flood_prediction_pipeline.predict_and_log scheduled__2025-10-19T10:50:00+00:00 [queued]>
[2025-10-19T10:55:05.405+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-10-19T10:55:05.425+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): predict_and_log> on 2025-10-19 10:50:00+00:00
[2025-10-19T10:55:05.442+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'flood_prediction_pipeline', 'predict_and_log', 'scheduled__2025-10-19T10:50:00+00:00', '--job-id', '365', '--raw', '--subdir', 'DAGS_FOLDER/flood_prediction_dag.py', '--cfg-path', '/tmp/tmpv8cybufd']
[2025-10-19T10:55:05.445+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1527) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-10-19T10:55:05.448+0000] {standard_task_runner.py:91} INFO - Job 365: Subtask predict_and_log
[2025-10-19T10:55:05.448+0000] {standard_task_runner.py:63} INFO - Started process 1530 to run task
[2025-10-19T10:55:05.523+0000] {task_command.py:426} INFO - Running <TaskInstance: flood_prediction_pipeline.predict_and_log scheduled__2025-10-19T10:50:00+00:00 [running]> on host d59dd3e0b4a4
[2025-10-19T10:55:05.670+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='flood_prediction_pipeline' AIRFLOW_CTX_TASK_ID='predict_and_log' AIRFLOW_CTX_EXECUTION_DATE='2025-10-19T10:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-19T10:50:00+00:00'
[2025-10-19T10:55:05.673+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-19T10:55:07.197+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/sklearn/ensemble/_base.py:168 UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
[2025-10-19T10:55:07.207+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/sklearn/ensemble/_base.py:168 UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
[2025-10-19T10:55:07.405+0000] {logging_mixin.py:188} WARNING - 2025/10/19 10:55:07 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2025-10-19T10:55:07.742+0000] {logging_mixin.py:188} INFO - ‚ö†Ô∏è Warning: could not log artifact to MLflow: [Errno 13] Permission denied: '/mlflow'
[2025-10-19T10:55:07.822+0000] {logging_mixin.py:188} INFO - üèÉ View run Live Flood Prediction at: http://mlflow:5000/#/experiments/1/runs/fa41d87521f6417eb3f93c851bef983a
[2025-10-19T10:55:07.826+0000] {logging_mixin.py:188} INFO - üß™ View experiment at: http://mlflow:5000/#/experiments/1
[2025-10-19T10:55:07.898+0000] {logging_mixin.py:188} INFO - ‚úÖ Prediction logged: {'prediction': 1, 'probability': 0.98, 'timestamp': '2025-10-19 10:55:07'}
[2025-10-19T10:55:07.899+0000] {python.py:237} INFO - Done. Returned value was: {'prediction': 1, 'probability': 0.98, 'timestamp': '2025-10-19 10:55:07'}
[2025-10-19T10:55:07.901+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-19T10:55:07.938+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=flood_prediction_pipeline, task_id=predict_and_log, run_id=scheduled__2025-10-19T10:50:00+00:00, execution_date=20251019T105000, start_date=20251019T105505, end_date=20251019T105507
[2025-10-19T10:55:07.996+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-10-19T10:55:08.013+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
