[2025-10-28T16:14:51.030+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-28T16:14:51.120+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: model_retraining_pipeline.train_and_validate manual__2025-10-28T16:14:43.826869+00:00 [queued]>
[2025-10-28T16:14:51.147+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: model_retraining_pipeline.train_and_validate manual__2025-10-28T16:14:43.826869+00:00 [queued]>
[2025-10-28T16:14:51.159+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-10-28T16:14:51.197+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): train_and_validate> on 2025-10-28 16:14:43.826869+00:00
[2025-10-28T16:14:51.236+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=335) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-10-28T16:14:51.229+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'model_retraining_pipeline', 'train_and_validate', 'manual__2025-10-28T16:14:43.826869+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/retraining_pipeline.py', '--cfg-path', '/tmp/tmpei7q1jb0']
[2025-10-28T16:14:51.243+0000] {standard_task_runner.py:63} INFO - Started process 358 to run task
[2025-10-28T16:14:51.250+0000] {standard_task_runner.py:91} INFO - Job 35: Subtask train_and_validate
[2025-10-28T16:14:51.411+0000] {task_command.py:426} INFO - Running <TaskInstance: model_retraining_pipeline.train_and_validate manual__2025-10-28T16:14:43.826869+00:00 [running]> on host 42dce8a10814
[2025-10-28T16:14:51.745+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='model_retraining_pipeline' AIRFLOW_CTX_TASK_ID='train_and_validate' AIRFLOW_CTX_EXECUTION_DATE='2025-10-28T16:14:43.826869+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-28T16:14:43.826869+00:00'
[2025-10-28T16:14:51.750+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-28T16:14:51.939+0000] {logging_mixin.py:188} WARNING - 2025/10/28 16:14:51 INFO mlflow.tracking.fluent: Experiment with name 'Flood_Risk_Retrain' does not exist. Creating a new experiment.
[2025-10-28T16:14:52.217+0000] {logging_mixin.py:188} INFO - Skipping training due to: Insufficient valid data (0 rows) for training.
[2025-10-28T16:14:52.219+0000] {python.py:237} INFO - Done. Returned value was: {'f1': -2.0, 'recall': -2.0, 'run_id': 'skipped'}
[2025-10-28T16:14:52.220+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-28T16:14:52.267+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=model_retraining_pipeline, task_id=train_and_validate, run_id=manual__2025-10-28T16:14:43.826869+00:00, execution_date=20251028T161443, start_date=20251028T161451, end_date=20251028T161452
[2025-10-28T16:14:52.315+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-10-28T16:14:52.383+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-10-28T16:14:52.391+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
