[2025-10-28T17:45:05.802+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-28T17:45:05.826+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flood_prediction_pipeline.check_flood_risk scheduled__2025-10-28T17:40:00+00:00 [queued]>
[2025-10-28T17:45:05.835+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flood_prediction_pipeline.check_flood_risk scheduled__2025-10-28T17:40:00+00:00 [queued]>
[2025-10-28T17:45:05.835+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-10-28T17:45:05.849+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): check_flood_risk> on 2025-10-28 17:40:00+00:00
[2025-10-28T17:45:05.857+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'flood_prediction_pipeline', 'check_flood_risk', 'scheduled__2025-10-28T17:40:00+00:00', '--job-id', '250', '--raw', '--subdir', 'DAGS_FOLDER/flood_prediction_dag.py', '--cfg-path', '/tmp/tmpe0l5zabm']
[2025-10-28T17:45:05.858+0000] {standard_task_runner.py:91} INFO - Job 250: Subtask check_flood_risk
[2025-10-28T17:45:05.858+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=9342) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-10-28T17:45:05.859+0000] {standard_task_runner.py:63} INFO - Started process 9345 to run task
[2025-10-28T17:45:05.906+0000] {task_command.py:426} INFO - Running <TaskInstance: flood_prediction_pipeline.check_flood_risk scheduled__2025-10-28T17:40:00+00:00 [running]> on host 42dce8a10814
[2025-10-28T17:45:05.988+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='flood_prediction_pipeline' AIRFLOW_CTX_TASK_ID='check_flood_risk' AIRFLOW_CTX_EXECUTION_DATE='2025-10-28T17:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-28T17:40:00+00:00'
[2025-10-28T17:45:05.991+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-28T17:45:06.011+0000] {python.py:237} INFO - Done. Returned value was: no_alert_needed
[2025-10-28T17:45:06.012+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-28T17:45:06.032+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=flood_prediction_pipeline, task_id=check_flood_risk, run_id=scheduled__2025-10-28T17:40:00+00:00, execution_date=20251028T174000, start_date=20251028T174505, end_date=20251028T174506
[2025-10-28T17:45:06.073+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-10-28T17:45:06.090+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-10-28T17:45:06.094+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
