[2025-10-30T12:55:05.276+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-30T12:55:05.295+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flood_prediction_pipeline.log_to_database scheduled__2025-10-30T12:50:00+00:00 [queued]>
[2025-10-30T12:55:05.301+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flood_prediction_pipeline.log_to_database scheduled__2025-10-30T12:50:00+00:00 [queued]>
[2025-10-30T12:55:05.302+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-10-30T12:55:05.314+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): log_to_database> on 2025-10-30 12:50:00+00:00
[2025-10-30T12:55:05.322+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=4595) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-10-30T12:55:05.322+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'flood_prediction_pipeline', 'log_to_database', 'scheduled__2025-10-30T12:50:00+00:00', '--job-id', '386', '--raw', '--subdir', 'DAGS_FOLDER/flood_prediction_dag.py', '--cfg-path', '/tmp/tmp2sjhvmcn']
[2025-10-30T12:55:05.323+0000] {standard_task_runner.py:63} INFO - Started process 4598 to run task
[2025-10-30T12:55:05.323+0000] {standard_task_runner.py:91} INFO - Job 386: Subtask log_to_database
[2025-10-30T12:55:05.360+0000] {task_command.py:426} INFO - Running <TaskInstance: flood_prediction_pipeline.log_to_database scheduled__2025-10-30T12:50:00+00:00 [running]> on host 19da7fe5fa41
[2025-10-30T12:55:05.584+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='flood_prediction_pipeline' AIRFLOW_CTX_TASK_ID='log_to_database' AIRFLOW_CTX_EXECUTION_DATE='2025-10-30T12:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-30T12:50:00+00:00'
[2025-10-30T12:55:05.587+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-30T12:55:05.605+0000] {logging_mixin.py:188} INFO - ℹ️ No data to log.
[2025-10-30T12:55:05.606+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-10-30T12:55:05.607+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-30T12:55:05.617+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=flood_prediction_pipeline, task_id=log_to_database, run_id=scheduled__2025-10-30T12:50:00+00:00, execution_date=20251030T125000, start_date=20251030T125505, end_date=20251030T125505
[2025-10-30T12:55:05.659+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-10-30T12:55:05.678+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-10-30T12:55:05.682+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
