[2025-10-30T15:30:05.804+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-30T15:30:05.835+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flood_prediction_pipeline.log_to_database scheduled__2025-10-30T15:25:00+00:00 [queued]>
[2025-10-30T15:30:05.844+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flood_prediction_pipeline.log_to_database scheduled__2025-10-30T15:25:00+00:00 [queued]>
[2025-10-30T15:30:05.846+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-10-30T15:30:05.860+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): log_to_database> on 2025-10-30 15:25:00+00:00
[2025-10-30T15:30:05.868+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'flood_prediction_pipeline', 'log_to_database', 'scheduled__2025-10-30T15:25:00+00:00', '--job-id', '123', '--raw', '--subdir', 'DAGS_FOLDER/flood_prediction_dag.py', '--cfg-path', '/tmp/tmpjis1rjda']
[2025-10-30T15:30:05.869+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2134) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-10-30T15:30:05.870+0000] {standard_task_runner.py:91} INFO - Job 123: Subtask log_to_database
[2025-10-30T15:30:05.870+0000] {standard_task_runner.py:63} INFO - Started process 2137 to run task
[2025-10-30T15:30:05.918+0000] {task_command.py:426} INFO - Running <TaskInstance: flood_prediction_pipeline.log_to_database scheduled__2025-10-30T15:25:00+00:00 [running]> on host ef4a724a1397
[2025-10-30T15:30:05.990+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='flood_prediction_pipeline' AIRFLOW_CTX_TASK_ID='log_to_database' AIRFLOW_CTX_EXECUTION_DATE='2025-10-30T15:25:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-30T15:25:00+00:00'
[2025-10-30T15:30:05.993+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-30T15:30:06.011+0000] {logging_mixin.py:188} INFO - ℹ️ No data to log.
[2025-10-30T15:30:06.012+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-10-30T15:30:06.013+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-30T15:30:06.019+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=flood_prediction_pipeline, task_id=log_to_database, run_id=scheduled__2025-10-30T15:25:00+00:00, execution_date=20251030T152500, start_date=20251030T153005, end_date=20251030T153006
[2025-10-30T15:30:06.045+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-10-30T15:30:06.064+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-10-30T15:30:06.068+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
