[2025-10-29T17:45:10.947+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-29T17:45:10.988+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flood_prediction_pipeline.check_flood_risk scheduled__2025-10-29T17:40:00+00:00 [queued]>
[2025-10-29T17:45:11.005+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flood_prediction_pipeline.check_flood_risk scheduled__2025-10-29T17:40:00+00:00 [queued]>
[2025-10-29T17:45:11.006+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-10-29T17:45:11.023+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): check_flood_risk> on 2025-10-29 17:40:00+00:00
[2025-10-29T17:45:11.035+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=11494) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-10-29T17:45:11.034+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'flood_prediction_pipeline', 'check_flood_risk', 'scheduled__2025-10-29T17:40:00+00:00', '--job-id', '154', '--raw', '--subdir', 'DAGS_FOLDER/flood_prediction_dag.py', '--cfg-path', '/tmp/tmpmwohfkx0']
[2025-10-29T17:45:11.036+0000] {standard_task_runner.py:63} INFO - Started process 11497 to run task
[2025-10-29T17:45:11.037+0000] {standard_task_runner.py:91} INFO - Job 154: Subtask check_flood_risk
[2025-10-29T17:45:11.124+0000] {task_command.py:426} INFO - Running <TaskInstance: flood_prediction_pipeline.check_flood_risk scheduled__2025-10-29T17:40:00+00:00 [running]> on host db3c1202c602
[2025-10-29T17:45:11.268+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='flood_prediction_pipeline' AIRFLOW_CTX_TASK_ID='check_flood_risk' AIRFLOW_CTX_EXECUTION_DATE='2025-10-29T17:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-29T17:40:00+00:00'
[2025-10-29T17:45:11.272+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-29T17:45:11.298+0000] {python.py:237} INFO - Done. Returned value was: no_alert_needed
[2025-10-29T17:45:11.299+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-29T17:45:11.325+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=flood_prediction_pipeline, task_id=check_flood_risk, run_id=scheduled__2025-10-29T17:40:00+00:00, execution_date=20251029T174000, start_date=20251029T174510, end_date=20251029T174511
[2025-10-29T17:45:11.372+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-10-29T17:45:11.401+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-10-29T17:45:11.407+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
